Add some environment vars and a warning if there's no config.yml file

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,6 +12,11 @@ BOLD=$(tput bold)
 NORMAL=$(tput sgr0)
 INSTALLATION_TYPE="bare"
 
+if [ ! -f "config.yml" ]; then
+  echo "File config.yml not found."
+  exit 1
+fi
+
 if [ -x "$(command -v docker)" ] && [ -x "$(command -v docker-compose)" ]; then
   INSTALLATION_TYPE="docker"
 fi
@@ -35,12 +40,16 @@ then
   # We need robo to set up the environment.
   ( docker run --user ${USER_ID}:${GROUP_ID} \
     --name php_install --rm -it \
+    -e HOME="/tmp" \
+    -e COMPOSER_HOME="/tmp" \
     -v $(pwd):/var/www/html \
     -v $(pwd)/php.ini:/usr/local/etc/php/conf.d/php_overrides.ini \
     $PHP_IMAGE composer install )
 
   ( docker run --user ${USER_ID}:${GROUP_ID} \
     --name php_install --rm -it \
+    -e HOME="/tmp" \
+    -e COMPOSER_HOME="/tmp" \
     -v $(pwd):/var/www/html \
     -v $(pwd)/php.ini:/usr/local/etc/php/conf.d/php_overrides.ini \
     $PHP_IMAGE ./bin/robo pse --type docker )
@@ -69,7 +78,7 @@ COMMAND=$([ "$ENVIRONMENT" == "development" ] && echo "composer install" || echo
 
 # Install.
 if [ $INSTALLATION_TYPE == "docker" ]; then
-  docker run --user ${USER_ID}:${GROUP_ID} --name php_install --rm -it -v $(pwd):/var/www/html $PHP_IMAGE $COMMAND \
+  docker run --user ${USER_ID}:${GROUP_ID} --name php_install --rm -it -e HOME="/tmp" -e COMPOSER_HOME="/tmp" -v $(pwd):/var/www/html $PHP_IMAGE $COMMAND \
   && docker-compose -f docker/docker-compose.yml up -d \
   && sleep 10 \
   && docker exec -u ${USER_ID} php bin/robo piu $FORCE
